### PR TITLE
Support multiple epheremal constants in Newton steps for mes4cgp and …

### PR DESCRIPTION
**Pull request by hejung**
…momes4cgp via Hessian inversion through eigen.
I added the same code for mes and momes, brief outline:
First check how many epheremal constants are actually part of expression, if it is only one no calls to eigen are made. If more construct reduced size hessian, do some checks and do a newton step only if they are all met.

As opposed to the previous PR #58 I now use the FullPivLU instead of a Choelsky decomposition, because I do not like the idea to see if the Hessian is positive definite by checking if the Choelsky failed (since the Choelsky only works on positive definite matrices). Using the FullPivLU (which does not have any constraints on the matrix) and checking explicitly feels much more sane to me.

### CODE REVIEW

**Comment by darioizzo** [comment]
I reviewed the logic on this and seems fine. I am inclined to accept it, but I was wondering whether it has been tested on some cases? I am a bit worried no tests cover this code. 

Maybe  the code should be moved out on some utility and tested there?

**Comment by hejung** [comment]
I have tested sofar only in ipython notebooks on a few of the gym examples using MSE and on a couple of handcrafted examples to estimate the probability of success for binomial/multinomial draws using the CE loss. If you want I will upload them later.

I agree that it is probably a good idea to move the code to one place, especially since it is the same for mes4cgp and momes4cgp, so it would make testing much more straightforward.
What would be your preferred way to achieve this? I think I would go for a function that takes the proposed modified genomes ('mutated_x') with mutated discrete parts and modifies the continous parts inplace before returning? This would basically amount to move the whole livelong-learning part to a separate function except for the fitness evaluation (since it is different in momes4cgp and mes4cgp).
Let me know what you think/ what your preferred solution is.

**Comment by darioizzo** [comment]
Let me work on this in #64. I am refactoring and improving the code anyway. I should be done by today.

Then you could maybe halp testing and improving?

**Comment by darioizzo** [comment]
I am keeping most of your code, only some small refactors and changes ...

**Comment by hejung** [comment]
ok, let me know as soon as I can do anything.

**Comment by darioizzo** [comment]
Ok I pushed the mes and momes with the reduced hessian in #64 ... can you take a look and comment/test? 

If you agree I can merge that PR into master and you could then open new PRs for other improvements?

**Comment by darioizzo** [comment]
closing this as its now embeddd in #64

**Pull request closed without merging**
