### PR TITLE
[WIP] - Pr/misc

### PR DESCRIPTION
**Pull request by darioizzo**
A number of discussed and important feautres:
 - [x] Complete the UDA set with a multiobjective UDA (not memetic).
 - [x] Uniform UDAs constructors and argument naming.
 - [x] Vectorize the gduals in the UDP (x5 speed improvement)
 - [x] Solve the inversion issue (when eph constants are not in the expression).
 - [x] Investigate nan production
 - [x] Investigate formula display inconsistencies
 - [x] Update all old documentation to the new syntax.

### CODE REVIEW

**Comment by darioizzo** [comment]
Thanks for the reminder. I think its still a preferred pattern for dcgp than the non optional use_bfe arg in the uda constructor. The feature, as it is, remains hidden for most users. Power users will be able to play with it, but they will also be hopefully aware of the consequences (from the docs).

**Comment by hejung** [comment]
I have not tested yet, but the hessian inversion part looks good to me. I especially like the removal of complete rows/cols from the Hessian, looks much cleaner than what I did.

**Comment by darioizzo** [comment]
@hejung Yes the idea is clean, but I am not sure the implementation is correct ...

**Comment by darioizzo** [comment]
```c++
for (decltype(zero.size()) j = 0u; j < zero.size(); ++j) {
    remove_row(H, non_zero[j]);
    remove_column(H, non_zero[j]);
}
```
should maybe be:
```c++
for (decltype(zero.size()) j = 0u; j < zero.size(); ++j) {
    remove_row(H, non_zero[j] - j);
    remove_column(H, non_zero[j] - j);
}
```

**Comment by hejung** [comment]
I agree that the second version is correct. The other one would have resulted in the wrong rows/cols being deleted after the row/col has been deleted.

ATM I am a bit unsure on how I would test it inside of the algorithm (i.e. the whole construction coming from pagmo), but what I can do for sure is write a test that uses a matrix and a couple of indices to delete in random order and that checks that we will always end up with what we expect.
Will still think about a more complete test also.

**Comment by darioizzo** [comment]
Thanks. Yes testing properly that part of the code for correctness is difficult. At this stage, before the release of v1.5, if would be nice if you could just give an independent confirmation (even if just from local experiments)  that what I wrote makes sense and behaves accordingly.

**Comment by darioizzo** [comment]
In the meantime I will merge this. We can fix bugs and test on a different PR

**Pull request merged**
